name: jack
version: 0.6.0

description: >
  Jack.
homepage: https://github.com/comigor/jack

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  freezed_annotation: ^2.2.0
  intl:
  money2: ^3.3.0
  petitparser: ^5.1.0

dev_dependencies:
  build_runner: ^2.3.3
  freezed: ^2.3.2
  lints: ^2.0.1
  test: ^1.22.2
