name: jack
version: 0.7.0

description: >
  Jack.
homepage: https://github.com/comigor/jack

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  freezed_annotation: ^2.2.0
  intl:
  money2: ^4.0.0
  petitparser: ^6.0.1

dev_dependencies:
  build_runner: ^2.4.6
  freezed: ^2.4.3
  lints: ^2.1.1
  test: ^1.24.7
