on: pull_request

name: CI

jobs:
  check-version-and-changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: comigor/actions/check-version-and-changelog@master
        with:
          repo_token: ${{ github.token }}
          base_ref: ${{ github.base_ref }}
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1.3
        with:
          sdk: stable
      - id: install
        name: Install dependencies
        run: dart pub get
      - name: Test
        if: always() && steps.install.outcome == 'success'
        run: dart test
